GET http://localhost:8080/api/posts

###
POST http://localhost:8080/api/posts
Content-Type: application/json

{"content": "the Post"}

###
POST http://localhost:8080/api/posts
Content-Type: application/json

{"id": 3, "content": "the Post NEW"}

###
DELETE http://localhost:8080/api/posts/2
###
GET http://localhost:8080/api/posts/2
###
GET http://localhost:8080/api/posts/removed
